version: "3"
services:
  rembg-app:
    build: .  # This builds from your local Dockerfile
    # image: alyetama/rembg-app:latest  # Comment this out
    ports:
      - "8501:8501"
    command: >
      streamlit run streamlit_app.py
    restart: always
    volumes:
      - "./.streamlit:/home/app/.streamlit"
      - "./streamlit_app.py:/home/app/streamlit_app.py"  # Mount your updated file